version: "3.8"

services:

  mongo:
    image:  mongodb/mongodb-community-server # use iamge id or you can also use image name 
    container_name: mongo
    networks:
      - my-net
    restart: always
    ports:
      - "270017:27017"

  backend:
    build: ./backend
    container_name: my-backend
    networks:
      - my-net
    restart: always
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mean_db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: my-frontenddd
    networks: 
      - my-net
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - backend

    nginx:
    image: 6eab9bd31d06 # use image id or you can also use image name
    container_name: my-nginxtttt
    networks:
      - my-net
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

      
